export default function Home({data}) {
    console.log(data)

    const postHtml= data.map ((post,i) => {
        return(
            <p key={post.id}>{post.title.rendered}</p>
        )
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
        </div>
    )
}

export async function getServerSideProps(context) {
    const res = await fetch (`http://harrypotterfanblog.local/hello-world/`)
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }
    return {
        props:{
            data
        },
    }
}